variables:
  # App Specifications
  MIN_CPU: 50m
  MIN_MEMORY: 128Mi
  MAX_CPU: 100m
  MAX_MEMORY: 256Mi
  PORT: 3000

  # Image and Deployment Variables
  VERSION: $CI_COMMIT_TAG
  TAG_IMAGE_NAME: "$registry_host/$CI_PROJECT_PATH:$VERSION"
  APP_NAME: "$CI_PROJECT_NAME"
  INGRESS_HOST: "$CI_PROJECT_PATH_SLUG"

  # App Variables
  PODS_NEXT_PUBLIC_API_URL_BE: "https://kelompok-7-brewforce-be.pkpl.cs.ui.ac.id"
  PODS_NEXT_PUBLIC_API_URL_AUTH: "https://kelompok-7-brewforce-auth.pkpl.cs.ui.ac.id"
  PODS_TEST: tests